### ISSUE TITLE
Feature request: Replace current mapping with the one used in mod-data-import 

### ISSUE THREAD

**Issue by fontanka16** [ChalmersLibrary/chami#2]
Chami's mapping is built on the same mapping proposal from the FOLIO community  as the [mod-data loader mapping](https://s3.amazonaws.com/foliodocs/api/mod-data-loader/loader.html#), but since they are not in the same code base these two will diverge eventually.

The proposal here is to rebuild Chami's Marc-to-Instance mapping with the one developed for mod-data-import module

**Comment by branchedelac** [comment]
@fontanka16, does this affect how I should approach https://github.com/ChalmersLibrary/chami/issues/9? 

Update: I did #9, the same way we've approached it so far, anyway.

**Comment by branchedelac** [comment]
After discussing this with @fontanka16, we (Chalmers) decided that for the near future, we'll continue working with the custom mapping we have in Chami. This is definitely something that we might want to revisit in the future, though, and that might be interesting to other libraries using FOLIO with LIBRIS.
